# The original workflow has been replaced by a variant of the one used in twodsix and xdy-pf2e-workbench
name: Test and release

# Run the workflow when a Pull Request is opened or when changes are pushed to main on 'marvin9257/fvtt-token-action-hud-twodsix' (i.e. don't run on forks)
on:
  pull_request:
  push:
    branches: [ main ]

jobs:

  release:
    # Only release on push to main on marvin9257/fvtt-token-action-hud-twodsix
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main') && github.repository == 'marvin9257/fvtt-token-action-hud-twodsix'
    runs-on: ubuntu-latest
    ## Waits for test jobs for each Node.js version to complete
    #needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Send Webhook Notification
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: bash src/scripts/discord.sh $WEBHOOK_URL
        shell: bash

      - name: Install playwright
        run: npx playwright install

      - name: Publish to Foundry VTT Repo
        id: publish_foundry_repo
        run: npx @ghost-fvtt/foundry-publish
        env:
          FVTT_MANIFEST_PATH: 'module.json'
          FVTT_PACKAGE_ID: ${{ secrets.FOUNDRY_ADMIN_PACKAGE_ID }}
          FVTT_USERNAME: ${{ secrets.FOUNDRY_ADMIN_USERNAME }}
          FVTT_PASSWORD: ${{ secrets.FOUNDRY_ADMIN_PASSWORD }}
